name: edrixs_tutorial
channels:
  - conda-forge
dependencies:
  - jupyterlab=3.*
  - jupytext
  - jupyterlab-mathjax3>=4.3
  - edrixs>=0.0.8
  - ipympl=0.9.*
  - ipywidgets=8.*
  - nodejs
  - openmpi
  - unzip
  - bokeh=3.0.*
  - h5py
  - hdf5
  - seaborn
  - sphinx-gallery
  - myst-nb
  - sphinx-book-theme
  - sphinx-design
  - sphinx-copybutton
