#!/usr/bin/env bash
set -eux

pip install threadpoolctl
mkdir -p ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings
cp .binder/overrides.json ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings/overrides.json
